apiVersion: batch/v1
kind: Job
metadata:
  name: run-tests
  namespace: test-build
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pytest
        image: python:3.9-slim
        workingDir: /workspace
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt-get update && apt-get install -y git &&
            git clone https://github.com/BulkMazurka/kaniko-build.git /workspace &&
            cd /workspace/repo/build &&
            pip install -r requirements.txt &&
            pytest -q

