apiVersion: batch/v1
kind: Job
metadata:
  name: run-tests
  namespace: test-build
spec:
  backoffLimit: 0          # do not retry on failure (fail fast)
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pytest
        image: python:3.9-slim
        workingDir: /workspace   
        - args:
           - apt-get update && apt-get install -y git && \   # install Git
           - git clone https://github.com/BulkMazurka/kaniko-build.git /workspace && \ 
           - cd /workspace/build && \                        # go into the build/ folder
           - pip install -r requirements.txt && \            # install app dependencies
           - pytest -q                                        # run tests quietly (pytest)
      volumes:
      - name: workspace
        emptyDir: {}                         
      volumeMounts:
      - name: workspace
        mountPath: /workspace
